---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root

  tasks:
    - name: Collection of log files from Server1
      fetch:
        src: /var/log/syslog
        dest: /home/kennethllave/Documents/server1_logfiles/
        flat: yes
